#!/usr/bin/env python3
"""Generate the share-code field table from the markup that defines it.

A share code is positional: field 7 is field 7 because the table says so, and
every existing code decodes against that table.  So the table has to be an exact
description of the controls, and it has to stay one.

Hand-writing it would be the ``presets.py`` mistake a second time.  That module
exists to reproduce "what ``frontend/index.html`` actually submits", it drifted,
and ``ligand_bond_mm`` sat at 1.2 on one side and 1.4 on the other until someone
turned ligands on.  A second hand-maintained copy of every slider's range is the
same bug wearing a different name, so this reads the range off the control.

Usage::

    python scripts/build_share_table.py           # rewrite the table in place
    python scripts/build_share_table.py --check    # fail if it is out of date

``--check`` is the one that matters: it turns "somebody widened a slider and
every shared link now decodes to the wrong number" into a failing command.

Changing a slider's min/max/step, or reordering the fields, changes what an old
code means.  When that happens the table is *not* simply regenerated: bump
``SHARE_FORMAT`` in the front end and keep the old table alongside, or accept
that codes minted before the change are wrong rather than merely stale.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(HERE, "frontend", "index.html")

BEGIN = "  /* SHARE-TABLE-BEGIN — generated by scripts/build_share_table.py */"
END = "  /* SHARE-TABLE-END */"

#: Segmented groups a person actually drives.  ``use_magnets`` is deliberately
#: absent: it is a legacy control that ``syncAssembly`` writes from the Assembly
#: fork and the Magnets switch, so encoding it would be storing the same answer
#: twice and inviting the two copies to disagree.
SEG_FIELDS = [
    "protein_rep", "nucleic_rep", "backbone_style", "base_style",
    "ligand_style", "assembly", "no_magnet_method", "magnet_shape",
    "magnet_count", "dna_magnet_count",
]

#: Segmented groups added *after* the sliders were already in the table, which
#: is why they are not in ``SEG_FIELDS`` above.
#:
#: A share code stores a 6-bit **field index**, so what a code means depends
#: entirely on a field's position in this list.  Appending is safe; inserting is
#: not.  Adding ``cartoon_hbonds`` to ``SEG_FIELDS`` would have pushed all four
#: checkboxes and all twenty-five sliders down one place, and every link anyone
#: had already shared would have decoded to a different scale, a different wall
#: thickness and a different set of magnets — silently, because the code would
#: still be structurally valid.  That is why these go on the end instead.
#:
#: Anything added from here on belongs in one of the LATE_ lists, never in the
#: original three.
LATE_SEG_FIELDS = ["cartoon_hbonds"]

#: Checkboxes that reach the payload.  ``connect`` is absent for the same reason
#: as ``use_magnets`` — it is driven, not chosen.
BOOL_FIELDS = ["include_ligands", "magnets", "socket", "basepair_connect"]


def _sliders(html: str) -> list:
    out = []
    for m in re.finditer(r'data-slider="([a-z_]+)"', html):
        name = m.group(1)
        window = html[m.end():m.end() + 900]
        inp = re.search(r"<input type=\"range\"([^>]*)>", window)
        if not inp:
            continue
        at = dict(re.findall(r'(min|max|step|value)="([-\d.]+)"', inp.group(1)))
        if not {"min", "max", "step"} <= set(at):
            raise SystemExit(
                f"slider {name!r} is missing min/max/step — a share code cannot "
                f"encode a control whose range is not declared")
        lo, hi, st = float(at["min"]), float(at["max"]), float(at["step"])
        n = int(round((hi - lo) / st)) + 1
        default = float(at.get("value", lo))
        out.append({
            "k": name, "t": "s",
            "lo": lo, "st": st, "n": n,
            "d": int(round((default - lo) / st)),
        })
    if not out:
        raise SystemExit("no sliders found — has the markup changed shape?")
    return out


def _segs(html: str, names=None) -> list:
    out = []
    for name in (SEG_FIELDS if names is None else names):
        # Anchored on the element, not on the attribute: the same string
        # appears in the script below as a selector, and matching that would
        # read the options out of nothing.
        m = re.search(r'<div class="seg[^"]*" data-group="%s"' % re.escape(name),
                      html)
        if not m:
            raise SystemExit(f"segmented group {name!r} is not in the markup")
        window = html[m.end():m.end() + 2000]
        cut = window.find("</div>")
        body = window[:cut] if cut >= 0 else window
        buttons = re.findall(r"<button([^>]*)>", body)
        values, default = [], 0
        for b in buttons:
            v = re.search(r'data-value="([^"]+)"', b)
            if not v:
                continue
            if "active" in b:
                default = len(values)
            values.append(v.group(1))
        if not values:
            raise SystemExit(f"segmented group {name!r} has no options")
        out.append({"k": name, "t": "g", "v": values, "d": default})
    return out


def _bools(html: str) -> list:
    out = []
    for name in BOOL_FIELDS:
        m = re.search(r'<input type="checkbox" id="%s"([^>]*)>' % re.escape(name),
                      html)
        if not m:
            raise SystemExit(f"checkbox {name!r} is not in the markup")
        out.append({"k": name, "t": "b", "d": 1 if "checked" in m.group(1) else 0})
    return out


def table(html: str) -> list:
    """Field order is the format. Appending is safe; reordering is not.

    New controls go on the **end**, after the sliders, whatever kind they are —
    see ``LATE_SEG_FIELDS``.  The original three groups are frozen in this order
    because every share code ever minted decodes against it.
    """
    return (_segs(html) + _bools(html) + _sliders(html)
            + _segs(html, LATE_SEG_FIELDS))


def render(fields: list) -> str:
    lines = [BEGIN,
             "  // Do not edit by hand — see scripts/build_share_table.py.",
             "  // Order is the wire format: append only, never reorder.",
             "  const SHARE_FIELDS = ["]
    for f in fields:
        lines.append("    " + json.dumps(f, separators=(",", ":")) + ",")
    lines.append("  ];")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the table is out of date")
    args = ap.parse_args()

    html = open(INDEX, encoding="utf-8").read()
    if BEGIN not in html or END not in html:
        raise SystemExit("the SHARE-TABLE markers are not in frontend/index.html")

    fresh = render(table(html))
    start = html.index(BEGIN)
    stop = html.index(END) + len(END)
    current = html[start:stop]

    if current == fresh:
        print(f"share table is current ({len(table(html))} fields)")
        return 0
    if args.check:
        print("share table is OUT OF DATE — run scripts/build_share_table.py",
              file=sys.stderr)
        print("A control's range or the field order changed. Every share code "
              "minted before that change now decodes to different values: bump "
              "SHARE_FORMAT rather than regenerating quietly.", file=sys.stderr)
        return 1
    open(INDEX, "w", encoding="utf-8").write(html[:start] + fresh + html[stop:])
    print(f"share table written ({len(table(html))} fields)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
